# Generated by Django 5.2.7 on 2025-11-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_review', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
