# Generated by Django 5.2.7 on 2025-11-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_review', '0004_userprofile_phone_number_userprofile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='project_review/company_logos/')),
                ('location', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('rating_count', models.IntegerField()),
                ('price_range', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('promoted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('startup', 'Startup'), ('investor', 'Investor')], default='startup', max_length=10),
        ),
    ]
