# Generated by Django 5.2.7 on 2025-11-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_review', '0006_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='file_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='registration',
            name='startup_idea_report',
            field=models.FileField(blank=True, null=True, upload_to='project_review/startup_reports/'),
        ),
    ]
