# Generated by Django 5.2.7 on 2025-11-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_review', '0008_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='portal_password',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
