# Generated by Django 5.2.7 on 2026-02-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_review', '0009_registration_portal_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(blank=True, max_length=20)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gateway_login',
            },
        ),
    ]
