# Generated by Django 5.2.7 on 2026-02-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_review', '0010_gatewaylogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about_company',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_profile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
