# Generated by Django 5.2.7 on 2026-02-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_review', '0011_userprofile_about_company_userprofile_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='startup_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='startup_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
