# Generated by Django 5.2.7 on 2026-02-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_review', '0013_loginhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginhistory',
            name='is_registered',
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
