# Generated by Django 5.2.7 on 2026-02-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_review', '0014_remove_loginhistory_is_registered_loginhistory_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gst_invoice',
            field=models.FileField(blank=True, null=True, upload_to='project_review/investor_invoices/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='investment_focus',
            field=models.TextField(blank=True, null=True),
        ),
    ]
