# Generated by Django 5.2.7 on 2026-02-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_review', '0015_userprofile_gst_invoice_userprofile_investment_focus'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='investor_role_in_company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
