# Generated by Django 5.2.7 on 2026-02-17 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_review', '0016_userprofile_investor_role_in_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('investor_role_in_company', models.CharField(blank=True, max_length=255, null=True)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('about_company', models.TextField(blank=True, null=True)),
                ('investment_focus', models.TextField(blank=True, null=True)),
                ('gst_invoice', models.FileField(blank=True, null=True, upload_to='project_review/investor_records/invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
