# Generated by Django 5.2.7 on 2026-02-17 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_review', '0019_portalmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='about_company',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='company_website',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gst_invoice',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='investment_focus',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='investor_role_in_company',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='linkedin_profile',
        ),
    ]
