# Generated by Django 5.2.7 on 2026-02-17 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_review', '0020_remove_userprofile_about_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('abstract', models.TextField()),
                ('inventors', models.TextField()),
                ('assignee', models.CharField(blank=True, max_length=255)),
                ('patent_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='profile_text',
            field=models.TextField(blank=True, help_text='Startup Description'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='team_size',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='project_review.registration')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueness_score', models.FloatField(default=0.0)),
                ('patent_similarity_score', models.FloatField(default=0.0)),
                ('ownership_status', models.CharField(blank=True, max_length=100)),
                ('verdict', models.CharField(blank=True, max_length=50)),
                ('explanation', models.TextField(blank=True)),
                ('matched_references', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation_result', to='project_review.registration')),
            ],
        ),
    ]
