# Generated by Django 5.2.7 on 2026-02-17 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_review', '0021_patentdocument_alter_registration_profile_text_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatentDocument',
        ),
        migrations.DeleteModel(
            name='ValidationResult',
        ),
    ]
