# Generated by Django 5.2.7 on 2026-02-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_review', '0023_userprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='startup_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
