# Generated by Django 5.2.7 on 2026-02-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_review', '0024_userprofile_startup_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('startup', 'Startup'), ('investor', 'Investor'), ('admin', 'Admin')], default='startup', max_length=10),
        ),
    ]
