# Generated by Django 5.2.7 on 2026-02-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_review', '0025_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='is_registered',
            field=models.IntegerField(default=0),
        ),
    ]
