# Generated by Django 5.2.7 on 2026-02-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_review', '0026_loginhistory_is_registered'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedUserRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('date_joined', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('portal_password', models.CharField(blank=True, max_length=128, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
