# Generated by Django 5.2.7 on 2026-02-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_review', '0027_deleteduserrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleteduserrecord',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
