# Generated by Django 5.2.7 on 2026-02-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_review', '0028_deleteduserrecord_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleteduserrecord',
            name='password_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
