# Generated by Django 5.2.7 on 2026-02-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_review', '0029_deleteduserrecord_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='startup_linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
