# Generated by Django 5.2.7 on 2026-02-27 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_review', '0030_userprofile_startup_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalmessage',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_messages', to='project_review.registration'),
        ),
    ]
