# Generated by Django 5.2.7 on 2026-03-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_review', '0031_portalmessage_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='github_profile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
