# Generated by Django 5.2.7 on 2026-03-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_review', '0032_userprofile_github_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='startup_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
