# Generated by Django 5.2.7 on 2026-03-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_review', '0034_directmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='admin_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='admin_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='gst_extracted_from_invoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='gst_verification_status',
            field=models.CharField(choices=[('Verified', 'Verified'), ('Invalid', 'Invalid'), ('Pending', 'Pending'), ('Not Uploaded', 'Not Uploaded')], default='Not Uploaded', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='gst_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='gstin_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='linkedin_last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='linkedin_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='trust_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='verification_status',
            field=models.CharField(choices=[('Verified Profile', 'Verified Profile'), ('Needs Review', 'Needs Review'), ('Suspicious', 'Suspicious'), ('Unverified', 'Unverified')], default='Unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='website_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Unreachable', 'Unreachable'), ('Suspicious', 'Suspicious'), ('Unknown', 'Unknown')], default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='website_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='patent_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='registration',
            name='patent_status',
            field=models.CharField(choices=[('Verified', 'Verified'), ('Invalid', 'Invalid'), ('Pending', 'Pending'), ('Not Provided', 'Not Provided')], default='Not Provided', max_length=20),
        ),
        migrations.AddField(
            model_name='registration',
            name='patent_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='trust_score',
            field=models.IntegerField(default=0),
        ),
    ]
