# Generated by Django 5.2.7 on 2026-03-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_review', '0035_company_admin_approved_company_admin_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='patent_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='patent_status',
            field=models.CharField(choices=[('Verified', 'Verified'), ('Invalid', 'Invalid'), ('Pending', 'Pending'), ('Not Provided', 'Not Provided')], default='Not Provided', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='patent_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trust_score',
            field=models.IntegerField(default=0),
        ),
    ]
