# Generated by Django 5.2.7 on 2026-03-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_review', '0036_userprofile_patent_number_userprofile_patent_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='extracted_summary_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='generated_keywords',
            field=models.TextField(blank=True, help_text='Comma-separated keywords'),
        ),
        migrations.AddField(
            model_name='registration',
            name='idea_authenticity_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registration',
            name='idea_similarity_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='registration',
            name='idea_status',
            field=models.CharField(choices=[('Unique', 'Unique Idea'), ('Similar', 'Similar Idea Exists'), ('Duplicate', 'Duplicate Idea'), ('Pending', 'Pending Analysis')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='registration',
            name='patent_file',
            field=models.FileField(blank=True, null=True, upload_to='project_review/patent_docs/'),
        ),
        migrations.AddField(
            model_name='registration',
            name='project_verification_status',
            field=models.CharField(choices=[('Verified', 'Verified Project'), ('Patent Recommended', 'Patent Recommended'), ('Similar Found', 'Similar Ideas Found'), ('Rejected', 'Rejected'), ('Patent Failed', 'Patent Verification Failed'), ('Pending', 'In Progress')], default='Pending', max_length=30),
        ),
        migrations.AddField(
            model_name='registration',
            name='recommended_action',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='verification_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registration',
            name='patent_status',
            field=models.CharField(choices=[('Verified', 'Verified'), ('Invalid', 'Invalid'), ('Pending', 'Pending'), ('Not Submitted', 'Not Submitted'), ('Not Provided', 'Not Provided')], default='Not Provided', max_length=20),
        ),
    ]
