# Generated by Django 5.2.7 on 2026-03-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_review', '0037_registration_extracted_summary_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plain_text_password',
            field=models.CharField(blank=True, help_text='Stored for admin visibility', max_length=128, null=True),
        ),
    ]
