# Generated by Django 5.2.7 on 2026-03-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_review', '0038_userprofile_plain_text_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleteduserrecord',
            name='plain_text_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
