# Generated by Django 5.2.7 on 2026-03-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_review', '0039_deleteduserrecord_plain_text_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='patent_detailed_status',
            field=models.CharField(blank=True, default='In Processing', max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='patent_owner',
            field=models.CharField(blank=True, default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='registration',
            name='patent_registry',
            field=models.CharField(blank=True, default='Unknown Registry', max_length=100),
        ),
    ]
