# Generated by Django 5.2.7 on 2026-03-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_review', '0040_registration_patent_detailed_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='gst_center_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='gst_legal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='gst_registration_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='gst_taxpayer_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
