# Generated by Django 5.2.7 on 2026-04-17 15:21

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_review', '0042_aichatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatmessage',
            name='intent_tag',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aichatmessage',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='promoted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='registration',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_number',
            field=models.CharField(db_index=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('startup', 'Startup'), ('investor', 'Investor'), ('admin', 'Admin')], db_index=True, default='startup', max_length=10),
        ),
        migrations.AddIndex(
            model_name='aichatmessage',
            index=models.Index(fields=['user', 'timestamp'], name='project_rev_user_id_5be969_idx'),
        ),
        migrations.AddIndex(
            model_name='aichatmessage',
            index=models.Index(fields=['intent_tag'], name='project_rev_intent__fab148_idx'),
        ),
    ]
